### ISSUE TITLE
Mail bei geringem Lagerbestand

### ISSUE THREAD

**Issue by Stefko** [richardhj/contao-isotope_simple_stockmanagement#10]
Bei den Produkttypen habe ich den Haken gesetzt, dass eine Mail verschickt wird, wenn ein Schwellenwert erreicht wird. Das klappt soweit auch, allerdings fehlt mir die Info, welches Produkt diese Mail auslöst, also welches Produkt seinen Schwellenwert erreicht hat.
Ich beschreibe hier mal mein bisheriges Vorgehen:
- Produkttypen -> [check] bei Benachrichtigung verschicken wenn Schwellwert erreicht wird
- Im Notificationcenter eine Benachrichtigung erstellt "Lagerbestand gering" vom Typ "`iso_stockmanagement_change`"
Soweit klappt das wie gesagt auch.
Ich würde dieser Nachricht aber zB gerne einen Text geben wie "_Produkt ##produkt## ist nur noch gering verfügbar_".
Als SimpleToken bekomme ich dort nur ##product_*## vorgeschlagen und dieser Token wird nicht aufgelöst, sondern exakt so in der Mail (Plaintext) angezeigt.

Übersehe ich da was, mache ich was falsch, oder handelt es sich hier um einen Bug bzw ist mein Wunsch aktuell so gar nicht umsetzbar?
Danke

**Comment by richardhj** [comment]
Du verwendest als Token bspw. `##product_name##`?

**Comment by Stefko** [comment]
Nein, ich versuchte es tatsächlich mit ##product_*## in der Annahme, das der * durch das Produkt ersetzt wird, welches die Mail triggert. Also eine Mailvorlage für alle Produkte.

**Comment by richardhj** [comment]
Wie auch bei den Isotope Benachrichtigungen muss das `*` durch ein Attribute des Produkts bzw. eine Spalte in der Datenbank ersetzt werden.
Mögliche Tokens wären also: `product_name`, `product_price`, `product_sku`.

Es wird automatisch das getriggerte Produkt eingefügt.

**Comment by Stefko** [comment]
Perfekt, so funktioniert es. Danke
