### ISSUE TITLE
Lagerbestand bei Varianten wird nicht berücksichtigt

### ISSUE THREAD

**Issue by mpitz** [richardhj/contao-isotope_simple_stockmanagement#17]
Wenn man Varianten eines Produktes hat, werden bei den Varianten zwar die Bestellungen im Lagerbestand gezählt (also auch abgezogen), allerdings nicht vom Gesamt-Lagerbestand abgezogen:

In der Variante:
![image](https://user-images.githubusercontent.com/6831223/134122415-5f3f88f2-c68b-4e64-9e35-92e85b5f4eb1.png)

Im Gesamtbestand:
![image](https://user-images.githubusercontent.com/6831223/134122500-1ec899a4-7771-4099-a434-b7d0af77aafc.png)

**Comment by richardhj** [comment]
Wie besprochen, es ist nicht unterstützt, dass der Stock des Hauptprodukts genutzt wird beim Kauf von Varianten.
