### ISSUE TITLE
Mengenberechnung falsch - Isotope 2.4.1, Contao 2.5.27

### ISSUE THREAD

**Issue by gintabln** [richardhj/contao-isotope_simple_stockmanagement#3]
Vielen Dank für die Erweiterung!
Folgendes Problem: sobald die Lagerverwaltung aktiv ist, wird nur die erte Bestellung durchgeführt. Danach, unabhängig davon, welche Menge noch vorhanden ist, wird das Prdukt als nicht länger verfügbar in Warenkorb angezeigt. Wen gleichzeitig noch "Produkte deaktivieren" aktiv ist, wird das Prdukt nach der ersten Bestellung deaktivert.
Leider ist im Backend  "Inventar-Einstellungen" mit Lagerbestand ebenfalls nicht sichtbar.
Woran könnte es liegen? 
Vielen Dank im Voraus.

**Comment by richardhj** [comment]
Hallo,

wird im Backend beim Produkt angezeigt, dass die Menge 0 ist?
Ansonsten lege mal folgende test.php-Datei an und schaue, was diese ausgibt (Produkt-ID einsetzen):
```php
<?php

define('TL_MODE', 'FE');
require('system/initialize.php');

$productId = 0;
var_dump(Isotope\Model\Stock::getStockForProduct($productId));
```
