### ISSUE TITLE
Product can be bought without positive stock

### ISSUE THREAD

**Issue by sgei** [richardhj/contao-isotope_simple_stockmanagement#6]
Hi,

First of all, thank you for the great extension.

I installed, configured and tested the extension.
I noticed that products without book goods can still be bought.
The inventory will be negative after the first order and the product will be deactivated.

I think it would be better if a stock of 0 is accepted with activated stock management and no stock booking?

Steffen

**Comment by richardhj** [comment]
I can introduce a checkbox called "Ignore stock management for these products until you added positive stock".
I guess I cannot introduce this as a default behavior within a patch release, thats why I suggest this checkbox.
What do you think?

**Comment by sgei** [comment]
Sounds good.
This would be a good way.

Do you already know when you release the next version? (the current stable realease is not working with Contao 3.5.33 + Isotope 2.4.5 - i have to use the dev-master)

Steffen

**Comment by richardhj** [comment]
> Do you already know when you release the next version? (the current stable realease is not working with Contao 3.5.33 + Isotope 2.4.5 - i have to use the dev-master)

Sorry I was assuming that everybody would use v2.0 on their own (even if in alpha). My fault.

**Comment by sgei** [comment]
Yes. I use the v2.0 alpha. This version is working well.
But if I install it with composer and I'm not an advanced user then I normaly use the stable one and this is v1.0.2.

Steffen

**Comment by richardhj** [comment]
No checkbox but
Implemented in 5e4a3233e017806b50bdb817d300c76732eacb77.

Available for testing at dev-master.

**Comment by sgei** [comment]
I have tested the changes. Everything works as expected.
Without an initial positive goods booking, the stock goes into negative territory.

If you have configured notifications, you will still get the message that the stock is, for example, less than 10.

Is it also possible to deactivate the messages if no initial positive goods bookings were made?

Thanks.

Steffen

**Comment by sgei** [comment]
Hi Richard,

> 
> If you have configured notifications, you will still get the message that the stock is, for example, less than 10.
> 
> Is it also possible to deactivate the messages if no initial positive goods bookings were made?

Can you make the following code change:

**Hooks.php**
Row: 215

from:
`if ($productType->stockmanagement_notification) {`
to:
`if ($productType->stockmanagement_notification  && false !== $stock) {`

I'm not sure if this is right, but it seems to work.

Thanks.

Steffen

**Comment by richardhj** [comment]
Implemented in b22abf3433b03b6e9abb8c10c4f0ea419c20a21c.

**Comment by sgei** [comment]
Danke!
