### ISSUE TITLE
Spaltenüberschrift "Änderungsdatum" in Inventar-Einstellungen fehlerhaft

### ISSUE THREAD

**Issue by sgei** [richardhj/contao-isotope_simple_stockmanagement#7]
Hallo,

in der Tabelle für die Lagerbestandsbuchungen gibt es eine Spalte Änderungsdatum.
Dort scheint ein Codierungsfehler zu sein.
Leider finde ich die Stelle nicht wo der Text definiert wird.

![lagerbestand](https://user-images.githubusercontent.com/2803995/36777474-e5ec0a04-1c69-11e8-811d-a2cfc9ae8b46.jpg)

Was und wo muss ich denn ändern, das die Ausgabe richtig ist?

Danke.

Steffen

**Comment by richardhj** [comment]
Die Sprachdatei liegt nicht in diesem Projekt. Der Text kommt aus Core-Dateien. Ggf. mal Contao-Check durchführen.
