### ISSUE TITLE
Anzeige Bestand im Backend

### ISSUE THREAD

**Issue by sgei** [richardhj/contao-isotope_simple_stockmanagement#8]
Hallo,

ich habe mal etwas rumgespielt und eine einfache Integration der Bestandsanzeige im Backend erstellt.
Sicher ist das nicht der ganz richtige Weg, aber es funktioniert.
Vielleicht kann Richard den Ansatz contao-konform mit in den Code unterbringen.

**zur prinzipiellen Idee:**

- es wird ein neues DB-Feld in der Tabelle tl_iso_product angelegt
- immer wenn der Bestand manuell über eine Lagerbestandsbuchung angepasst wird, wird das DB-Feld aktualisiert (BackendIntegration/Dca.php)
- immer wenn der Bestand aufgrund eines regulären Checkouts angepasst wird, wird das DB-Feld aktualisiert (FrontendIntegration/Hooks.php)
- eines neues Feld in der Produktliste zeigt den Bestand im Backend an

![show_stock_in_productlist](https://user-images.githubusercontent.com/2803995/37393139-87847d5e-2770-11e8-880d-534bc326f999.jpg)

### **Anzeigen des Lagerbestandes in der Produktliste im Contao-Isotope-Backend**

**1. ../system/config/dcaconfig.php**

```
// Hinzufügen eines neuen DB-Feldes
$GLOBALS['TL_DCA']['tl_iso_product']['fields']['p_stock'] = array
(
'label'	    => 'Bestand',
'inputType' => 'text',
'sql'       => "varchar(8) NOT NULL default '-'"
);
// Hinzufügen einer neuen Spalte in die Produktliste
if( is_array( $GLOBALS['TL_DCA']['tl_iso_product']['list']['label']['fields'] ) )
{
if ( !in_array( 'p_stock', $GLOBALS['TL_DCA']['tl_iso_product']['list']['label']['fields'] ) )
$GLOBALS['TL_DCA']['tl_iso_product']['list']['label']['fields'][] = 'p_stock';
}
```
Danach ist eine Aktualisierung der DB im Installtool nötig.

**2. ../composer/vendor/richardhj/contao-isotope_simple_stockmanagement/scr/BackendIntegration/Dca.php**

_ca. nach Zeile 23 einfügen:_

`use Contao\Database;`

_in der Funktion generateWizardList() vor dem "return $return;" folgendes einfügen:_

```
// BOF - update stock in tl_iso_product
$stock = \Richardhj\Isotope\SimpleStockManagement\Model\Stock::getStockForProduct($dcaWizard->currentRecord);
$stockMessage = (false === $stock) ? '-' : $stock;
$stockMessageNew = "'" . $stockMessage . "'";
Database::getInstance()
	->prepare("UPDATE tl_iso_product SET p_stock=$stockMessageNew WHERE id=$dcaWizard->currentRecord")
	->execute();
// EOF
```

**3. ../composer/vendor/richardhj/contao-isotope_simple_stockmanagement/scr/FrontendIntegration/Hooks.php**

_in der Funktion updateStockPostCheckout() am Ende des Blocks
"if ($productType->stockmanagement_active) {" folgendes einfügen:_

```
// BOF - update stock in tl_iso_product
$stockMessage = (false === $stock) ? '-' : $stock;
$stockMessageNew = "'" . $stockMessage . "'";
Database::getInstance()
	->prepare("UPDATE tl_iso_product SET p_stock=$stockMessageNew WHERE id=$product->id")
	->execute();
// EOF
```

**Comment by Stefko** [comment]
Sehr feine Sache, habe es eben mal getestet. Dabei sind mir zwei Dinge aufgefallen.
- In der Produktübersicht wird unter Bestand zuerst ein "-" angezeigt, öffnet man dann ein Produkt (bearbeiten) und klickt wieder auf "zurück" (speichern ist nicht nötig) erscheint dessen korrekter Bestand. Habe dann einfach über "mehrere Bearbeiten" alle geöffnet.
- Bei Varianten wird kein einzelner Bestand angezeigt.
Wie schon gesagt, tolle Sache. Wäre wirklich super, wenn das in die Erweiterung wandern würde, damit es update-fähig bleibt.

**Comment by sgei** [comment]
Hallo Stefko,

also bei mir wird der Bestand für Varianten angezeigt.

![show_stock_in_productlist_varianten](https://user-images.githubusercontent.com/2803995/37543712-ba48b7d4-2962-11e8-9ee5-4ae84bee1765.jpg)

Das mit dem "-" liegt daran, dass das neue DB-Feld initial diesen Wert hat und erst bei Bestandsaktualisierung geupdated wird.

Die Frontendanzeige für Varianten geht so: [Bestand Varianten Frontend](https://github.com/richardhj/contao-isotope_simple_stockmanagement/issues/4#issuecomment-373838171)

Steffen

**Comment by richardhj** [comment]
Implemented in 5bca23c19503bb15516c09d939006b8f6d921695.

**Comment by sgei** [comment]
Hallo Richard,

danke für Arbeit an der Backendanzeige.
Ich habe gerade getestet.

Für "normale" Produkte funktioniert es super!

![grafik](https://user-images.githubusercontent.com/2803995/37597872-eb1d9b66-2b80-11e8-932d-f18699cf1017.png)

Leider wird der Bestand bei Variantenansicht nicht angezeigt (siehe [hier](https://github.com/richardhj/contao-isotope_simple_stockmanagement/issues/11#issue-307539326))

Steffen

**Comment by richardhj** [comment]
Closing in favor of #11
